[build]
  functions = "netlify/functions"
  publish = "dist"
  command = "npm run build"

[dev]
  functions = "netlify/functions"
  publish = "dist"
  command = "npm run dev"
  port = 3000

[[plugins]]
package = "@netlify/plugin-functions-install-core"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200